// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteUserSearchQueryOperation OperationName = "DeleteUserSearchQuery"
	DeleteUserTokenSubOperation    OperationName = "DeleteUserTokenSub"
	GetUserSearchQueriesOperation  OperationName = "GetUserSearchQueries"
	GetUserTokenSubsOperation      OperationName = "GetUserTokenSubs"
	LogoutUserOperation            OperationName = "LogoutUser"
	SaveUserQueryOperation         OperationName = "SaveUserQuery"
	SearchTokenInfoOperation       OperationName = "SearchTokenInfo"
	SubscribeUserToTokenOperation  OperationName = "SubscribeUserToToken"
	UpdateUserTokenSubOperation    OperationName = "UpdateUserTokenSub"
	UserInfoOperation              OperationName = "UserInfo"
	VkAuthCallbackOperation        OperationName = "VkAuthCallback"
	VkAuthRegisterOperation        OperationName = "VkAuthRegister"
)
