// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/Error
type Error struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

type GetAllInterestBadRequest Error

func (*GetAllInterestBadRequest) getAllInterestRes() {}

type GetAllInterestInternalServerError Error

func (*GetAllInterestInternalServerError) getAllInterestRes() {}

type GetAllInterestOKApplicationJSON []Interest

func (*GetAllInterestOKApplicationJSON) getAllInterestRes() {}

// Ref: #/components/schemas/GetAllInterestRequest
type GetAllInterestRequest struct {
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *GetAllInterestRequest) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *GetAllInterestRequest) SetToken(val string) {
	s.Token = val
}

// Ref: #/components/schemas/Interest
type Interest struct {
	Timestamp int64            `json:"timestamp"`
	Features  InterestFeatures `json:"features"`
}

// GetTimestamp returns the value of Timestamp.
func (s *Interest) GetTimestamp() int64 {
	return s.Timestamp
}

// GetFeatures returns the value of Features.
func (s *Interest) GetFeatures() InterestFeatures {
	return s.Features
}

// SetTimestamp sets the value of Timestamp.
func (s *Interest) SetTimestamp(val int64) {
	s.Timestamp = val
}

// SetFeatures sets the value of Features.
func (s *Interest) SetFeatures(val InterestFeatures) {
	s.Features = val
}

type InterestFeatures struct {
	Interest int `json:"interest"`
}

// GetInterest returns the value of Interest.
func (s *InterestFeatures) GetInterest() int {
	return s.Interest
}

// SetInterest sets the value of Interest.
func (s *InterestFeatures) SetInterest(val int) {
	s.Interest = val
}
