// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteUserSearchQueryOperation OperationName = "DeleteUserSearchQuery"
	GetUserSearchQueriesOperation  OperationName = "GetUserSearchQueries"
	LogoutUserOperation            OperationName = "LogoutUser"
	SaveUserQueryOperation         OperationName = "SaveUserQuery"
	SearchTokenInfoOperation       OperationName = "SearchTokenInfo"
	VkAuthCallbackOperation        OperationName = "VkAuthCallback"
	VkAuthRegisterOperation        OperationName = "VkAuthRegister"
)
