// Code generated by ogen, DO NOT EDIT.
package api

type DeleteUserSearchQueryRes interface {
	deleteUserSearchQueryRes()
}

type GetUserSearchQueriesRes interface {
	getUserSearchQueriesRes()
}

type LogoutUserRes interface {
	logoutUserRes()
}

type SaveUserQueryRes interface {
	saveUserQueryRes()
}

type SearchTokenInfoRes interface {
	searchTokenInfoRes()
}

type UserInfoRes interface {
	userInfoRes()
}

type VkAuthCallbackRes interface {
	vkAuthCallbackRes()
}

type VkAuthRegisterRes interface {
	vkAuthRegisterRes()
}
