// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	LogoutUserOperation      OperationName = "LogoutUser"
	SearchTokenInfoOperation OperationName = "SearchTokenInfo"
	VkAuthCallbackOperation  OperationName = "VkAuthCallback"
	VkAuthRegisterOperation  OperationName = "VkAuthRegister"
)
