// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Example implements example operation.
//
// Example endpoint.
//
// POST /api/v1/domain/example
func (UnimplementedHandler) Example(ctx context.Context, req *ExampleDomainRequest) (r ExampleRes, _ error) {
	return r, ht.ErrNotImplemented
}
