// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/Error
type Error struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

type ExampleBadRequest Error

func (*ExampleBadRequest) exampleRes() {}

// Ref: #/components/schemas/ExampleDomainRequest
type ExampleDomainRequest struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Secret   string `json:"secret"`
}

// GetEmail returns the value of Email.
func (s *ExampleDomainRequest) GetEmail() string {
	return s.Email
}

// GetUsername returns the value of Username.
func (s *ExampleDomainRequest) GetUsername() string {
	return s.Username
}

// GetSecret returns the value of Secret.
func (s *ExampleDomainRequest) GetSecret() string {
	return s.Secret
}

// SetEmail sets the value of Email.
func (s *ExampleDomainRequest) SetEmail(val string) {
	s.Email = val
}

// SetUsername sets the value of Username.
func (s *ExampleDomainRequest) SetUsername(val string) {
	s.Username = val
}

// SetSecret sets the value of Secret.
func (s *ExampleDomainRequest) SetSecret(val string) {
	s.Secret = val
}

// Ref: #/components/schemas/ExampleDomainResponse
type ExampleDomainResponse struct {
	Message string `json:"message"`
	Length  int    `json:"length"`
}

// GetMessage returns the value of Message.
func (s *ExampleDomainResponse) GetMessage() string {
	return s.Message
}

// GetLength returns the value of Length.
func (s *ExampleDomainResponse) GetLength() int {
	return s.Length
}

// SetMessage sets the value of Message.
func (s *ExampleDomainResponse) SetMessage(val string) {
	s.Message = val
}

// SetLength sets the value of Length.
func (s *ExampleDomainResponse) SetLength(val int) {
	s.Length = val
}

func (*ExampleDomainResponse) exampleRes() {}

type ExampleUnauthorized Error

func (*ExampleUnauthorized) exampleRes() {}
