// Code generated by ogen, DO NOT EDIT.
package api

type LogoutUserRes interface {
	logoutUserRes()
}

type SearchTokenInfoRes interface {
	searchTokenInfoRes()
}

type VkAuthCallbackRes interface {
	vkAuthCallbackRes()
}

type VkAuthRegisterRes interface {
	vkAuthRegisterRes()
}
