name: cd

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: log in to image registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          
          IMAGE=ghcr.io/${{ github.repository_owner }}/vixarapi
          TAG_SHA=${IMAGE}:${SHORT_SHA}
          TAG_LATEST=${IMAGE}:latest
          
          docker build \
            --file build/image/Dockerfile \
            --tag $TAG_SHA \
            --tag $TAG_LATEST \
            .

      - name: push docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/vixarapi:${GITHUB_SHA:0:7}
          docker push ghcr.io/${{ github.repository_owner }}/vixarapi:latest
